name = "times-table-hero"
compatibility_date = "2024-11-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "tth-db"
database_id = "aa4f2487-7923-49e8-ba0e-89504a8f010a"
migrations_dir = "migrations"
